---
- name: This playbook is for installating or upgrading Networker
  hosts: linux_clients
  become: yes
  

  tasks:
  - name: Create a symbolic link
    shell:
      cmd: . /home/oracle/19c.env; cd ${ORACLE_HOME}/lib; ln -s /usr/lib/libnsrora.so libobk.so
