---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
            - vim
            - curl
            - nano
            -  bc
            - binutils
            - elfutils-libelf
            - elfutils-libelf-devel
            - fontconfig-devel
            - glibc
            - glibc-devel
            - ksh
            - libaio
            - libaio-devel
            - libXrender
            - libX11
            - libXau
            - libXi
            - libXtst
            - libgcc
            - libnsl
            - librdmacm
            - libstdc++
            - libstdc++-devel
            - libxcb
            - libibverbs
            - make
            - smartmontools
            - sysstat

