---
- name: Creating a User with Ansible Playbook
  hosts: "{{ target_hosts }}"
  become: yes
  vars:
    target_hosts: app_servers
  vars_prompt:
    - name: user_password
      prompt: "Enter the password for the new user:"
      private: yes
  tasks:
    - name: Create the user
      user:
        name: "{{ a }}"
        password: "{{ user_password | password_hash('sha512', 'SomeSalt') }}"
        home: "{{ c }}"
        uid: "{{ d }}"
        shell: "{{ e }}"
